export const COLLABORATIONS: string[] = [
  'Arturia',
  'Balo',
  'Blansable',
  'LVMH',
  'Hurrah.Group',
  'Justin buisson',
  'LivMed’s',
  'Ok Dream',
  'Matthieu Braccini',
  'Matteyyy',
  'ZQSD Productions',
  'TrackmaniaCup 2022',
  'Mekalabs (Mekaverse)',
  'Yoplait',
  'Vyder',
  '3kelo',
  'Valorant France',
  'Soulware',
  'Heirvey',
  'SNCF',
  'Lacoste',
  'Scaleway',
  'Hervé Studio',
  'Mujo Atelier',
  'Virtex',
  'Popcorn',
  'MINI',
  'BMW',
  'Averse',
  'FFF',
  'Gaspard G',
];
